version: "3.9"
services:
  app:
    build:
      context: .
    container_name: django-app
    ports:
      - "8000:8000"
    entrypoint: sh /tmp/entrypoint.sh
    volumes:
      - ./safety_site:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "82:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mikhailroot01@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - default

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/static
      - ./media:/media
      - ./uploads:/uploads
      - ./detections:/detections
      - ./neural_networks:/neural_networks
      - ./nginx/:/etc/nginx/conf.d/:ro
    depends_on:
      - app
    networks:
      - default

  redis:
    container_name: redis
    image: redis:latest
    command: >
      sh -c "redis-server"
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  postgres_data:

networks:
  default: